# Site settings
title: Peer 2 Peer University
email: admin@p2pu.org
description: "A University for the Web. Built by an open community. LEARNING BY EVERYONE. FOR
EVERYONE. ABOUT ALMOST ANYTHING. COMPLETELY FREE."
baseurl:
url: "http://p2pu.org"
languages: ['en', 'es']
default_language: 'en'

# Build settings
markdown: kramdown
permalink: pretty

#SASS settings
sass:
  sass_dir: _sass
  style: :compressed

env: prod

exclude: [Guardfile, Gemfile, Gemfile.lock, README]









